### ISSUE TITLE
Support for ghc-9.0.1

### ISSUE THREAD

**Issue by jneira** [haskell/stylish-haskell#378]
* I guess this needs to be updated to ghc-lib-parser-9.0.1
* The unique issue i've seen about is #370

**Comment by Ailrun** [comment]
@jaspervdj, is there any news on this? It would be appreciated if we can hear some plans or difficulties.

**Comment by michaelpj** [comment]
Even better if we could get 9.2.1 support as well!

**Comment by jaspervdj** [comment]
I started a branch for the jump to 9.2.  There's been a fair amount of changes that impact how we use the API.  Overall they're improvements so they'll give me an opportunity to clean up some stuff.  I expect to finish this in a couple of weeks.

**Comment by Mikolaj** [comment]
Is there a branch one compile to have stylish-haskell work with GHC 9.2.1/2?

**Comment by jaspervdj** [comment]
> Is there a branch one compile to have stylish-haskell work with GHC 9.2.1/2?

@Mikolaj You can try the `ghc-9.2` branch.  Everything should work fine except the `data` step which will be skipped.

**Comment by Mikolaj** [comment]
Thank you for the hint. I've just tried it, with GHC 9.2.2 and got:

```
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: stylish-haskell, ghc-lib-parser-ex,
text, template-haskell, base, ghc-boot, ghc-lib-parser-ex:auto
```

Not 100% sure it's stylish-haskell's fault. I haven't tried with GHC 9.2.1.

**Comment by Mikolaj** [comment]
Thank you! But something weird happened --- newest commits are now from 2013.

**Comment by Mikolaj** [comment]
And on branch ghc-9.2 with GHC 9.2.2 I'm still having

```
~/r/stylish-haskell$ cabal install --minimize-conflict-set
Error: cabal: Could not resolve dependencies:
[__0] trying: stylish-haskell-0.13.0.0 (user goal)
[__1] next goal: text (dependency of stylish-haskell)
[__1] rejecting: text-1.2.5.0/installed-1.2.5.0 (conflict: stylish-haskell =>
bytestring>=0.9 && <0.11, text => bytestring==0.11.3.0/installed-0.11.3.0)
[__1] rejecting: text-2.0 (conflict: stylish-haskell => text>=1.2 && <1.3)
[__1] trying: text-1.2.5.0
[__2] trying: template-haskell-2.18.0.0/installed-2.18.0.0 (dependency of
text)
[__3] trying: ghc-lib-parser-ex-9.2.0.3 (dependency of stylish-haskell)
[__4] trying: ghc-lib-parser-ex:+auto
[__5] next goal: ghc-boot (dependency of ghc-lib-parser-ex +auto)
[__5] rejecting: ghc-boot-9.2.2/installed-9.2.2 (conflict: stylish-haskell =>
bytestring>=0.9 && <0.11, ghc-boot => bytestring==0.11.3.0/installed-0.11.3.0)
[__5] rejecting: ghc-boot-9.2.1 (conflict: template-haskell =>
ghc-boot-th==9.2.2/installed-9.2.2, ghc-boot => ghc-boot-th==9.2.1)
[__5] rejecting: ghc-boot-9.0.1 (conflict: template-haskell =>
base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.7 && <4.16)
[__5] rejecting: ghc-boot-8.8.3, ghc-boot-8.8.1 (conflict: template-haskell =>
base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.11 && <4.14)
[__5] rejecting: ghc-boot-8.6.5, ghc-boot-8.6.4, ghc-boot-8.6.1 (conflict:
template-haskell => base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.10
&& <4.13)
[__5] rejecting: ghc-boot-8.4.4, ghc-boot-8.4.3, ghc-boot-8.4.2,
ghc-boot-8.4.1 (conflict: template-haskell =>
base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.8 && <4.12)
[__5] rejecting: ghc-boot-8.2.2, ghc-boot-8.2.1 (conflict: template-haskell =>
base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.8 && <4.11)
[__5] rejecting: ghc-boot-8.0.2, ghc-boot-8.0.1 (conflict: template-haskell =>
base==4.16.1.0/installed-4.16.1.0, ghc-boot => base>=4.7 && <4.10)
[__5] fail (backjumping, conflict set: ghc-boot, ghc-lib-parser-ex,
stylish-haskell, template-haskell, ghc-lib-parser-ex:auto)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: stylish-haskell, ghc-lib-parser-ex,
template-haskell, text, ghc-boot, base, ghc-lib-parser-ex:auto
```

**Comment by Mikolaj** [comment]
And indeed

    ~/r/stylish-haskell$ cabal install --minimize-conflict-set --allow-newer

fails with

```
[ 4 of 26] Compiling Language.Haskell.Stylish.GHC ( lib/Language/Haskell/Stylish/GHC.hs, dist/build/Language/Haskell/Stylish/GHC.o, dist/build/Language/Haskell/Stylish/GHC.dyn_o )

lib/Language/Haskell/Stylish/GHC.hs:71:32: error:
    • Couldn't match expected type ‘GHC.Settings’
                  with actual type ‘ghc-9.2.2:GHC.Settings.Settings’
      NB: ‘GHC.Settings’
            is defined in ‘GHC.Settings’
                in package ‘ghc-lib-parser-9.2.2.20220307’
          ‘ghc-9.2.2:GHC.Settings.Settings’
            is defined in ‘GHC.Settings’ in package ‘ghc-9.2.2’
    • In the first argument of ‘defaultDynFlags’, namely
        ‘GHCEx.fakeSettings’
      In the expression:
        defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
      In an equation for ‘baseDynFlags’:
          baseDynFlags
            = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |
71 | baseDynFlags = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |                                ^^^^^^^^^^^^^^^^^^
```

**Comment by Mikolaj** [comment]
GHC 9.2.2

**Comment by jaspervdj** [comment]
@Mikolaj I've published a metadata revision to hackage (and the `main` branch) that allows bytestring-0.11.  Would you mind trying again with that?  I got it working using GHC-9.2.1, I haven't been able to try GHC-9.2.2 yet.

**Comment by Mikolaj** [comment]
@jaspervdj: but the error https://github.com/haskell/stylish-haskell/issues/378#issuecomment-1069611182 is not a dep version problem, right?

**Comment by jaspervdj** [comment]
@Mikolaj correct, but I think the error there is the result of using `--allow-newer`, which seems to result in a bad mix of `ghc-lib-parser` and `ghc-lib-parser-ex`. Can you try it without `--allow-newer`?  I'll look into using the newer versions of those libraries, they should be compatible.

**Comment by Mikolaj** [comment]
Makes sense, but sadly I'm getting

```
~/waste$ cabal update
Downloading the latest package list from hackage.haskell.org
Updated package list of hackage.haskell.org to the index-state 2022-03-17T11:10:50Z
To revert to previous state run:
    cabal v2-update 'hackage.haskell.org,2022-03-16T15:54:09Z'
~/waste$ cabal install stylish-haskell
...
[ 4 of 26] Compiling Language.Haskell.Stylish.GHC ( lib/Language/Haskell/Stylish/GHC.hs, dist/build/Language/Haskell/Stylish/GHC.o, dist/build/Language/Haskell/Stylish/GHC.dyn_o )

lib/Language/Haskell/Stylish/GHC.hs:71:32: error:
    • Couldn't match expected type ‘GHC.Settings’
                  with actual type ‘ghc-9.2.2:GHC.Settings.Settings’
      NB: ‘GHC.Settings’
            is defined in ‘GHC.Settings’
                in package ‘ghc-lib-parser-9.2.2.20220307’
          ‘ghc-9.2.2:GHC.Settings.Settings’
            is defined in ‘GHC.Settings’ in package ‘ghc-9.2.2’
    • In the first argument of ‘defaultDynFlags’, namely
        ‘GHCEx.fakeSettings’
      In the expression:
        defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
      In an equation for ‘baseDynFlags’:
          baseDynFlags
            = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |
71 | baseDynFlags = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |                                ^^^^^^^^^^^^^^^^^^

lib/Language/Haskell/Stylish/GHC.hs:71:51: error:
    • Couldn't match expected type ‘GHC.LlvmConfig’
                  with actual type ‘ghc-9.2.2:GHC.Driver.Session.LlvmConfig’
      NB: ‘GHC.LlvmConfig’
            is defined in ‘GHC.Driver.Session’
                in package ‘ghc-lib-parser-9.2.2.20220307’
          ‘ghc-9.2.2:GHC.Driver.Session.LlvmConfig’
            is defined in ‘GHC.Driver.Session’ in package ‘ghc-9.2.2’
    • In the second argument of ‘defaultDynFlags’, namely
        ‘GHCEx.fakeLlvmConfig’
      In the expression:
        defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
      In an equation for ‘baseDynFlags’:
          baseDynFlags
            = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |
71 | baseDynFlags = defaultDynFlags GHCEx.fakeSettings GHCEx.fakeLlvmConfig
   |                                                   ^^^^^^^^^^^^^^^^^^^^
```

**Comment by Mikolaj** [comment]
And the same on a branch called "main", after pulling.

**Comment by jaspervdj** [comment]
@Mikolaj I've uploaded a new version that picks dependencies based on what hlint does.  Would you mind trying again?  I verified this works on a blank ubuntu image with ghc-9.2.2.

**Comment by Mikolaj** [comment]
It works. \o/
