### ISSUE TITLE
style-haskell does not compile with stack lts-21.0 (ghc-9.4.5)

### ISSUE THREAD

**Issue by ciukstar** [haskell/stylish-haskell#463]
```stylish-haskell``` does not compile with ```stack``` lts-21.0 (ghc-9.4.5)
See error log below:
```
stylish-haskell              > configure
stylish-haskell              > Configuring stylish-haskell-0.14.5.0...
stylish-haskell              > build
stylish-haskell              > Preprocessing library for stylish-haskell-0.14.5.0..
stylish-haskell              > Building library for stylish-haskell-0.14.5.0..
stylish-haskell              > [ 1 of 26] Compiling Language.Haskell.Stylish.Block
stylish-haskell              > [ 2 of 26] Compiling Language.Haskell.Stylish.Config.Internal
stylish-haskell              > [ 3 of 26] Compiling Language.Haskell.Stylish.Editor
stylish-haskell              > [ 4 of 26] Compiling Language.Haskell.Stylish.GHC
stylish-haskell              > 
stylish-haskell              > /tmp/stack-57e8d6bfdb7fce67/stylish-haskell-0.14.5.0/lib/Language/Haskell/Stylish/GHC.hs:76:3: error:
stylish-haskell              >     Not in scope: data constructor ‘GHC.NewTypeCon’
stylish-haskell              >     NB: neither ‘GHC.Driver.Ppr’, ‘GHC.Driver.Session’, ‘GHC.Hs’,
stylish-haskell              >                 ‘GHC.Types.SrcLoc’ nor ‘GHC.Utils.Outputable’ export ‘NewTypeCon’.
stylish-haskell              >     Suggested fix: Perhaps use ‘GHC.NewType’ (imported from GHC.Hs)
stylish-haskell              >    |
stylish-haskell              > 76 |   GHC.NewTypeCon con -> [con]
stylish-haskell              >    |   ^^^^^^^^^^^^^^
stylish-haskell              > 
stylish-haskell              > /tmp/stack-57e8d6bfdb7fce67/stylish-haskell-0.14.5.0/lib/Language/Haskell/Stylish/GHC.hs:77:3: error:
stylish-haskell              >     Not in scope: data constructor ‘GHC.DataTypeCons’
stylish-haskell              >     NB: neither ‘GHC.Driver.Ppr’, ‘GHC.Driver.Session’, ‘GHC.Hs’,
stylish-haskell              >                 ‘GHC.Types.SrcLoc’ nor ‘GHC.Utils.Outputable’ export ‘DataTypeCons’.
stylish-haskell              >     Suggested fix: Perhaps use ‘GHC.DataType’ (imported from GHC.Hs)
stylish-haskell              >    |
stylish-haskell              > 77 |   GHC.DataTypeCons _ cons -> cons
stylish-haskell              >    |   ^^^^^^^^^^^^^^^^
stylish-haskell              > [22 of 26] Compiling Language.Haskell.Stylish.Verbose
stylish-haskell              > [23 of 26] Compiling Language.Haskell.Stylish.Config.Cabal
stylish-haskell              > [25 of 26] Compiling Paths_stylish_haskell
Completed 56 action(s).        

Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       [S-7011]
       While building package stylish-haskell-0.14.5.0 (scroll up to its section to see the error) using:
       /home/ss/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_6HauvNHV_3.8.1.0_ghc-9.4.5 --verbose=1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.8.1.0 build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1
```

**Comment by jaspervdj** [comment]
Is this using the `main` branch or the `0.14.5.0` release?  I just merged #464 which may fix it, so it would be useful if you could try the `main` branch.

**Comment by ciukstar** [comment]
> Is this using the `main` branch or the `0.14.5.0` release? I just merged #464 which may fix it, so it would be useful if you could try the `main` branch.

It now compiles and installs from main branch.
Thank you.
